"""Fixture data so the pipeline runs end-to-end before any real source is wired up.

Used by `priors preview` when no API keys are configured (Phase 0) and by tests.
All content below is clearly fake and labeled SAMPLE.
"""

from __future__ import annotations

from datetime import UTC, datetime

from priors.models import Article, Forecast, MarketMove, StoryImage, Take

SAMPLE_ARTICLES: list[Article] = [
    Article(
        id="sample-pol-1",
        url="https://example.com/politics/summit",
        title="[SAMPLE] Major powers conclude trade summit without agreement",
        source="Example Wire",
        published_at=datetime(2026, 7, 29, 9, 0, tzinfo=UTC),
        summary="Talks ended without a joint statement after three days.",
        section_hint="politics",
    ),
    Article(
        id="sample-pol-2",
        url="https://example.org/world/summit-analysis",
        title="[SAMPLE] What the failed summit means for supply chains",
        source="Example Journal",
        published_at=datetime(2026, 7, 30, 11, 0, tzinfo=UTC),
        summary="Analysts see tariff escalation as the base case.",
        section_hint="politics",
    ),
    Article(
        id="sample-biz-1",
        url="https://example.com/markets/chipmaker-earnings",
        title="[SAMPLE] Chipmaker beats estimates, guides down on datacenter demand",
        source="Example Wire",
        published_at=datetime(2026, 7, 28, 16, 0, tzinfo=UTC),
        summary="Shares fell 6% after hours despite the beat.",
        section_hint="business",
    ),
    Article(
        id="sample-sci-1",
        url="https://example.net/science/fusion-milestone",
        title="[SAMPLE] Lab reports sustained net-energy fusion for eight minutes",
        source="Example Science Desk",
        published_at=datetime(2026, 7, 27, 8, 0, tzinfo=UTC),
        summary="Independent replication is pending.",
        section_hint="scitech",
    ),
    Article(
        id="sample-custom-1",
        url="https://example.com/health/wearable-round",
        title="[SAMPLE] European stress-tech startup raises €12M Series A",
        source="Example Health Brief",
        published_at=datetime(2026, 7, 31, 7, 0, tzinfo=UTC),
        summary="The round was led by a Nordic fund.",
        section_hint="custom",
    ),
]

# Editorial fields used by the Phase 0 `write` stub. In Phase 1 these are
# composed by the LLM from the clustered articles; the stub exists so render
# and deliver have realistic input to work with.
SAMPLE_EDITORIAL: dict[str, dict] = {
    "sample-pol-1": {
        "headline": "[SAMPLE] Trade summit collapses; tariff escalation now the base case",
        "what_happened": (
            "Three days of talks between the major trading blocs ended without a joint "
            "statement. Negotiators failed to bridge differences on industrial subsidies. "
            "This is placeholder copy generated by the Phase 0 skeleton."
        ),
        "why_it_matters": (
            "If tariffs escalate, import-dependent manufacturers face margin pressure "
            "within two quarters. Second-order: sourcing diversification accelerates. "
            "Placeholder analysis — the real version is written by the LLM in Phase 1."
        ),
        "takes": [
            Take(
                source="Example Journal",
                source_url="https://example.org/world/summit-analysis",
                text="argues the collapse was choreographed for domestic audiences on both sides.",
            ),
            Take(
                source="Example Wire",
                source_url="https://example.com/politics/summit",
                text="notes that working-level channels remain open despite the public failure.",
            ),
        ],
        "forecasts": [
            Forecast(
                platform="polymarket",
                question="New tariffs announced by end of September?",
                probability=0.62,
                delta_pp=9.0,
                url="https://polymarket.com/sample-market",
            )
        ],
    },
    "sample-biz-1": {
        "headline": "[SAMPLE] The chip beat that spooked the market",
        "what_happened": (
            "A leading chipmaker beat quarterly estimates but guided down on datacenter "
            "demand, sending shares down 6% after hours. Placeholder copy."
        ),
        "why_it_matters": (
            "Guidance, not results, is doing the work: the market is repricing the "
            "capex cycle. Watch hyperscaler orders next month. Placeholder analysis."
        ),
        "takes": [
            Take(
                source="Example Wire",
                source_url="https://example.com/markets/chipmaker-earnings",
                text="reads the guidance cut as inventory digestion, not demand destruction.",
            )
        ],
        "no_market_note": True,
    },
    "sample-sci-1": {
        "headline": "[SAMPLE] Eight minutes of net-energy fusion, replication pending",
        "what_happened": (
            "A national lab reported sustained net-energy fusion for eight minutes, an "
            "order of magnitude beyond previous runs. Independent replication is pending. "
            "Placeholder copy."
        ),
        "why_it_matters": (
            "If replicated, timelines for pilot plants compress meaningfully — with "
            "knock-on effects for energy-intensive industry siting. Placeholder analysis."
        ),
        "takes": [
            Take(
                source="Example Science Desk",
                source_url="https://example.net/science/fusion-milestone",
                text="cautions that the diagnostic methodology has not been peer reviewed.",
            )
        ],
        "forecasts": [
            Forecast(
                platform="metaculus",
                question="Independent replication within 12 months?",
                probability=0.41,
                delta_pp=None,
                url="https://www.metaculus.com/sample-question",
            )
        ],
    },
    "sample-custom-1": {
        "headline": "[SAMPLE] €12M for stress tech: the nervous-system wearable thesis gets funded",
        "what_happened": (
            "A European startup building stress-monitoring wearables closed a €12M "
            "Series A led by a Nordic fund. Placeholder copy."
        ),
        "why_it_matters": (
            "Continued funding for the category validates investor appetite for "
            "physiology-based behavioral health. Placeholder analysis."
        ),
        "takes": [
            Take(
                source="Example Health Brief",
                source_url="https://example.com/health/wearable-round",
                text="sees the round as evidence that HRV-adjacent metrics are becoming standard.",
            )
        ],
        "no_market_note": True,
    },
}

SAMPLE_IMAGE = StoryImage(kind="card", url=None, attribution=None, attribution_url=None)

SAMPLE_MARKETS_MOVED: list[MarketMove] = [
    MarketMove(
        platform="polymarket",
        question="[SAMPLE] New tariffs announced by end of September?",
        probability=0.62,
        delta_pp=9.0,
        url="https://polymarket.com/sample-market",
    ),
    MarketMove(
        platform="kalshi",
        question="[SAMPLE] Fed cuts rates at the next meeting?",
        probability=0.28,
        delta_pp=-11.0,
        url="https://kalshi.com/sample-market",
    ),
    MarketMove(
        platform="metaculus",
        question="[SAMPLE] Independent fusion replication within 12 months?",
        probability=0.41,
        delta_pp=6.0,
        url="https://www.metaculus.com/sample-question",
    ),
]
